SPC_SOURCE_FILES 			= src/main.cpp $(SOURCE_FILES)
SPC_OBJECT_FILES 			= $(patsubst %.cpp,$(BUILD_DIRECTORY)/%.o, $(SPC_SOURCE_FILES))
SPC_DEPENDENCY_FILES 	= $(patsubst %.cpp,$(BUILD_DIRECTORY)/%.d, $(SPC_SOURCE_FILES))
SPC_LIBRARIES					= $(CORE_LIBRARY)
SPC_EXECUTABLE 				= $(BINARY_DIRECTORY)/spc

spc: CPP_INCLUDES += -I./include $(CORE_INCLUDES)
spc: $(SPC_EXECUTABLE)
	$(SPC_EXECUTABLE)

$(SPC_EXECUTABLE):	$(SPC_OBJECT_FILES) $(SPC_LIBRARIES)
	@$(MKDIR) $(@D)
	$(REMOVE) $(SPC_EXECUTABLE)
	$(LINKER) $^ -o $@

spc-clean:
	$(REMOVE) $(SPC_EXECUTABLE) $(SPC_OBJECT_FILES) $(SPC_DEPENDENCY_FILES)
	
.PHONY: spc-clean

-include $(SPC_DEPENDENCY_FILES)