SPC_TEST_SOURCE_FILES 			= test/main.cpp $(TEST_FILES) $(SOURCE_FILES)
SPC_TEST_OBJECT_FILES 			= $(patsubst %.cpp,$(BUILD_DIRECTORY)/%.o, $(SPC_TEST_SOURCE_FILES))
SPC_TEST_DEPENDENCY_FILES 	= $(patsubst %.cpp,$(BUILD_DIRECTORY)/%.d, $(SPC_TEST_SOURCE_FILES))
SPC_TEST_LIBRARIES					= $(CORE_LIBRARY) $(CBUNIT_LIBRARY)
SPC_TEST_EXECUTABLE 				= $(BINARY_DIRECTORY)/spc-test

spc-test: CPP_INCLUDES += $(CORE_INCLUDES) $(CBUNIT_INCLUDES) $(CBEXPECT_INCLUDES)
spc-test: CPP_COMPILER = $(CBUNIT) 
spc-test: $(SPC_TEST_EXECUTABLE)
	$(SPC_TEST_EXECUTABLE)

$(SPC_TEST_EXECUTABLE):	$(SPC_TEST_OBJECT_FILES) $(SPC_TEST_LIBRARIES)
	@$(MKDIR) $(@D)
	$(REMOVE) $(SPC_TEST_EXECUTABLE)
	$(LINKER) $^ -o $@

spc-test-clean:
	$(REMOVE) $(SPC_TEST_EXECUTABLE) $(SPC_TEST_OBJECT_FILES) $(SPC_TEST_DEPENDENCY_FILES)
	
.PHONY: spc-test-clean

-include $(SPC_TEST_DEPENDENCY_FILES)