CORE_DIRECTORY := ../Core

CORE_INCLUDES += -I$(MAKEFILE_DIRECTORY)$(CORE_DIRECTORY)/include

CORE_LIBRARY = lib/core.lib

$(CORE_LIBRARY):
	@make core -C $(MAKEFILE_DIRECTORY)$(CORE_DIRECTORY) \
		BUILD_DIRECTORY=$(MAKEFILE_DIRECTORY)$(BUILD_DIRECTORY)/cbcore \
		CORE_LIBRARY=$(MAKEFILE_DIRECTORY)$(CORE_LIBRARY)

.PHONY: $(CORE_LIBRARY)