CBUNIT_DIRECTORY := ../CBUnit

CBUNIT_LIBRARY = lib/cbunit.lib

CBUNIT_TOOL = utility/cbunit 

CBUNIT_INCLUDES = -I$(MAKEFILE_DIRECTORY)$(CBUNIT_DIRECTORY)/include

CBUNIT = $(CBUNIT_TOOL)

cbunit: $(CBUNIT_LIBRARY)

$(CBUNIT_LIBRARY):
	@make cbunit -C $(MAKEFILE_DIRECTORY)$(CBUNIT_DIRECTORY) \
		BUILD_DIRECTORY=$(MAKEFILE_DIRECTORY)$(BUILD_DIRECTORY)/cbunit \
		CBUNIT_COMMAND=$(MAKEFILE_DIRECTORY)$(CBUNIT_TOOL) \
		CBUNIT_LIBRARY=$(MAKEFILE_DIRECTORY)$(CBUNIT_LIBRARY)

.PHONY: $(CBUNIT_LIBRARY)